/**
 * Kociemba's two-phase solver, used to turn a random cube state into a scramble.
 *
 * Phase 1 drives the cube into the subgroup generated by <U, D, R2, L2, F2, B2>
 * — every corner and edge oriented, and the four equator edges somewhere in the
 * equator. Phase 2 then finishes within that subgroup, where no move can undo
 * the orientation work. Each phase is an IDA* search guided by pruning tables
 * holding the exact distance-to-goal for a pair of coordinates.
 *
 * Solutions are not optimal, and do not need to be: a scramble's quality comes
 * from the state being uniformly random, not from the move count. The search
 * simply stops once it has something short enough to look like a normal scramble.
 */

import {
  MOVE_CUBES,
  MOVE_NAMES,
  multiply,
  solvedCubie,
  type CubieCube,
} from './cubie';
import {
  N_CORNER_PERM,
  N_FLIP,
  N_SLICE,
  N_SLICE_PERM,
  N_TWIST,
  N_UD_EDGE_PERM,
  SLICE_SOLVED,
  cubeWithCoord,
  getCornerPerm,
  getFlip,
  getSlice,
  getSlicePerm,
  getTwist,
  getUdEdgePerm,
  setCornerPerm,
  setFlip,
  setSlice,
  setSlicePerm,
  setTwist,
  setUdEdgePerm,
} from './coords';

/** All 18 face turns, indexed face * 3 + (amount - 1) over U R F D L B. */
const PHASE1_MOVES: readonly number[] = Array.from({ length: 18 }, (_, i) => i);

/** U, D and the four half turns — the moves that stay inside the subgroup. */
const PHASE2_MOVES: readonly number[] = [0, 1, 2, 4, 7, 9, 10, 11, 13, 16];

const faceOf = (move: number): number => Math.floor(move / 3);
/** U/D, R/L and F/B commute, so only one order of each pair is worth searching. */
const isOppositeFace = (a: number, b: number): boolean => Math.abs(a - b) === 3;

const UNREACHABLE = 0xff;

interface Tables {
  twist: Uint16Array;
  flip: Uint16Array;
  slice: Uint16Array;
  cornerPerm: Uint16Array;
  udEdgePerm: Uint16Array;
  slicePerm: Uint16Array;
  pruneTwistSlice: Uint8Array;
  pruneFlipSlice: Uint8Array;
  pruneCornerSlice: Uint8Array;
  pruneEdgeSlice: Uint8Array;
}

let tables: Tables | null = null;

/**
 * Move tables map (coordinate, move) to the resulting coordinate. Each entry is
 * computed by applying the move to a cube carrying only that coordinate, using
 * loops specialised to the arrays involved so building 400k entries stays quick.
 */
function buildMoveTable(
  size: number,
  moves: readonly number[],
  set: (cube: CubieCube, value: number) => void,
  get: (cube: CubieCube) => number,
): Uint16Array {
  const table = new Uint16Array(size * moves.length);
  const scratch = solvedCubie();
  for (let coord = 0; coord < size; coord++) {
    const base = cubeWithCoord(set, coord);
    for (let m = 0; m < moves.length; m++) {
      const move = MOVE_CUBES[moves[m]];
      scratch.cp.set(base.cp);
      scratch.co.set(base.co);
      scratch.ep.set(base.ep);
      scratch.eo.set(base.eo);
      const moved = multiply(scratch, move);
      table[coord * moves.length + m] = get(moved);
    }
  }
  return table;
}

/**
 * Exact distance from every (a, b) coordinate pair to the goal, by breadth-first
 * search outwards from the goal. Both move sets are closed under inversion, so
 * distance from the goal equals distance to it.
 */
function buildPruningTable(
  sizeA: number,
  sizeB: number,
  moveA: Uint16Array,
  moveB: Uint16Array,
  moveCount: number,
  goalA: number,
  goalB: number,
): Uint8Array {
  const total = sizeA * sizeB;
  const distance = new Uint8Array(total).fill(UNREACHABLE);
  const queue = new Int32Array(total);
  let head = 0;
  let tail = 0;

  const start = goalA * sizeB + goalB;
  distance[start] = 0;
  queue[tail++] = start;

  while (head < tail) {
    const index = queue[head++];
    const next = distance[index] + 1;
    const a = (index / sizeB) | 0;
    const b = index - a * sizeB;
    const rowA = a * moveCount;
    const rowB = b * moveCount;
    for (let m = 0; m < moveCount; m++) {
      const target = moveA[rowA + m] * sizeB + moveB[rowB + m];
      if (distance[target] === UNREACHABLE) {
        distance[target] = next;
        queue[tail++] = target;
      }
    }
  }
  return distance;
}

const yieldToHost = (): Promise<void> => new Promise((resolve) => setTimeout(resolve, 0));

export interface PrepareProgress {
  step: number;
  total: number;
  label: string;
}

/**
 * The table build split into steps, so the async path can yield between them
 * and the synchronous path can just run them back to back.
 */
function buildSteps(): { steps: { label: string; run: () => void }[]; built: Partial<Tables> } {
  const built: Partial<Tables> = {};
  const steps = [
    {
      label: 'corner orientation',
      run: () => {
        built.twist = buildMoveTable(N_TWIST, PHASE1_MOVES, setTwist, getTwist);
      },
    },
    {
      label: 'edge orientation',
      run: () => {
        built.flip = buildMoveTable(N_FLIP, PHASE1_MOVES, setFlip, getFlip);
      },
    },
    {
      label: 'equator placement',
      run: () => {
        built.slice = buildMoveTable(N_SLICE, PHASE1_MOVES, setSlice, getSlice);
      },
    },
    {
      label: 'corner order',
      run: () => {
        built.cornerPerm = buildMoveTable(
          N_CORNER_PERM, PHASE2_MOVES, setCornerPerm, getCornerPerm,
        );
      },
    },
    {
      label: 'edge order',
      run: () => {
        built.udEdgePerm = buildMoveTable(
          N_UD_EDGE_PERM, PHASE2_MOVES, setUdEdgePerm, getUdEdgePerm,
        );
      },
    },
    {
      label: 'equator order',
      run: () => {
        built.slicePerm = buildMoveTable(
          N_SLICE_PERM, PHASE2_MOVES, setSlicePerm, getSlicePerm,
        );
      },
    },
    {
      label: 'orientation distances',
      run: () => {
        built.pruneTwistSlice = buildPruningTable(
          N_TWIST, N_SLICE, built.twist!, built.slice!, PHASE1_MOVES.length, 0, SLICE_SOLVED,
        );
        built.pruneFlipSlice = buildPruningTable(
          N_FLIP, N_SLICE, built.flip!, built.slice!, PHASE1_MOVES.length, 0, SLICE_SOLVED,
        );
      },
    },
    {
      label: 'permutation distances',
      run: () => {
        built.pruneCornerSlice = buildPruningTable(
          N_CORNER_PERM, N_SLICE_PERM, built.cornerPerm!, built.slicePerm!,
          PHASE2_MOVES.length, 0, 0,
        );
        built.pruneEdgeSlice = buildPruningTable(
          N_UD_EDGE_PERM, N_SLICE_PERM, built.udEdgePerm!, built.slicePerm!,
          PHASE2_MOVES.length, 0, 0,
        );
      },
    },
  ];
  return { steps, built };
}

/**
 * Builds the lookup tables, yielding between steps so a UI can stay responsive.
 * Roughly 4 MB of tables; the result is cached for the lifetime of the process.
 */
export async function prepareSolver(
  onProgress?: (progress: PrepareProgress) => void,
): Promise<void> {
  if (tables) return;
  const { steps, built } = buildSteps();
  for (let i = 0; i < steps.length; i++) {
    onProgress?.({ step: i, total: steps.length, label: steps[i].label });
    steps[i].run();
    await yieldToHost();
  }
  onProgress?.({ step: steps.length, total: steps.length, label: 'ready' });
  tables = built as Tables;
}

/** Builds the tables in one go, blocking until done. Used by tests. */
export function prepareSolverSync(): void {
  if (tables) return;
  const { steps, built } = buildSteps();
  for (const step of steps) step.run();
  tables = built as Tables;
}

export const isSolverReady = (): boolean => tables !== null;

export interface SolveOptions {
  /** Stop as soon as a solution this short is found. */
  targetLength?: number;
  /** Give up looking for something shorter after this long, in milliseconds. */
  timeBudgetMs?: number;
  /** Never return anything longer than this. */
  maxLength?: number;
}

/**
 * Returns move indices that solve the given state, or null if none was found
 * within the limits. A state that is already solved returns an empty array.
 */
export function solveCube(cube: CubieCube, options: SolveOptions = {}): number[] | null {
  if (!tables) throw new Error('solver tables are not built; call prepareSolver() first');
  const t = tables;
  const targetLength = options.targetLength ?? 21;
  const maxLength = options.maxLength ?? 26;
  const deadline = Date.now() + (options.timeBudgetMs ?? 600);

  const phase1Count = PHASE1_MOVES.length;
  const phase2Count = PHASE2_MOVES.length;

  // Held in an object rather than a bare `let`: it is assigned from inside the
  // nested search, which control-flow narrowing cannot follow.
  const result: { best: number[] | null } = { best: null };
  const path: number[] = [];

  const runPhase2 = (allowance: number): number[] | null => {
    // Replay phase 1 onto the real cube so the phase-2 coordinates are exact.
    let state = cube;
    for (const move of path) state = multiply(state, MOVE_CUBES[move]);

    let corner = getCornerPerm(state);
    let edge = getUdEdgePerm(state);
    let slice = getSlicePerm(state);
    if (corner === 0 && edge === 0 && slice === 0) return [];

    const solution: number[] = [];
    const search = (c: number, e: number, s: number, depth: number, lastFace: number): boolean => {
      if (depth === 0) return c === 0 && e === 0 && s === 0;
      const h = Math.max(t.pruneCornerSlice[c * N_SLICE_PERM + s], t.pruneEdgeSlice[e * N_SLICE_PERM + s]);
      if (h === UNREACHABLE || h > depth) return false;

      for (let m = 0; m < phase2Count; m++) {
        const face = faceOf(PHASE2_MOVES[m]);
        if (face === lastFace) continue;
        if (isOppositeFace(face, lastFace) && face > lastFace) continue;
        solution.push(PHASE2_MOVES[m]);
        const ok = search(
          t.cornerPerm[c * phase2Count + m],
          t.udEdgePerm[e * phase2Count + m],
          t.slicePerm[s * phase2Count + m],
          depth - 1,
          face,
        );
        if (ok) return true;
        solution.pop();
      }
      return false;
    };

    const lastFace = path.length ? faceOf(path[path.length - 1]) : -1;
    for (let depth = 1; depth <= allowance; depth++) {
      solution.length = 0;
      if (search(corner, edge, slice, depth, lastFace)) return [...solution];
    }
    return null;
  };

  const searchPhase1 = (
    twist: number,
    flip: number,
    slice: number,
    depth: number,
    lastFace: number,
  ): void => {
    if (result.best && result.best.length <= targetLength) return;
    if (Date.now() > deadline && result.best) return;

    if (depth === 0) {
      if (twist !== 0 || flip !== 0 || slice !== SLICE_SOLVED) return;
      const cap = (result.best ? result.best.length - 1 : maxLength) - path.length;
      if (cap < 0) return;
      const tail = runPhase2(Math.min(cap, 18));
      if (tail && (!result.best || path.length + tail.length < result.best.length)) {
        result.best = [...path, ...tail];
      }
      return;
    }

    const h = Math.max(
      t.pruneTwistSlice[twist * N_SLICE + slice],
      t.pruneFlipSlice[flip * N_SLICE + slice],
    );
    if (h === UNREACHABLE || h > depth) return;

    for (let m = 0; m < phase1Count; m++) {
      const face = faceOf(PHASE1_MOVES[m]);
      if (face === lastFace) continue;
      if (isOppositeFace(face, lastFace) && face > lastFace) continue;
      path.push(PHASE1_MOVES[m]);
      searchPhase1(
        t.twist[twist * phase1Count + m],
        t.flip[flip * phase1Count + m],
        t.slice[slice * phase1Count + m],
        depth - 1,
        face,
      );
      path.pop();
      if (result.best && result.best.length <= targetLength) return;
      if (Date.now() > deadline && result.best) return;
    }
  };

  const twist = getTwist(cube);
  const flip = getFlip(cube);
  const slice = getSlice(cube);

  for (let depth = 0; depth <= 12; depth++) {
    path.length = 0;
    searchPhase1(twist, flip, slice, depth, -1);
    if (result.best && (result.best.length <= targetLength || Date.now() > deadline)) break;
  }

  return result.best;
}

/** Human-readable form of a solution, e.g. "R U2 F' D". */
export const movesToText = (moves: readonly number[]): string =>
  moves.map((m) => MOVE_NAMES[m]).join(' ');

/** Reverses a move sequence, turning a solution into a scramble. */
export const invertMoveIndices = (moves: readonly number[]): number[] =>
  [...moves].reverse().map((move) => {
    const face = faceOf(move);
    const amount = (move % 3) + 1;
    const inverse = 4 - amount;
    return face * 3 + (inverse - 1);
  });
