using System.Text.Json; using SQLite; using CubeSolverPro.Core.Data;using CubeSolverPro.Core.Statistics;
namespace CubeSolverPro.App.Services.Storage;
public sealed class SqliteAppStore:IAppStore {SQLiteAsyncConnection? db;SQLiteAsyncConnection Db=>db??throw new InvalidOperationException("Store not initialized");static readonly JsonSerializerOptions Json=new(){PropertyNameCaseInsensitive=true};
 public async Task InitializeAsync(){if(db!=null)return;db=new SQLiteAsyncConnection(Path.Combine(FileSystem.AppDataDirectory,"cube-solver-pro.db3"),SQLiteOpenFlags.ReadWrite|SQLiteOpenFlags.Create|SQLiteOpenFlags.FullMutex);await Db.CreateTableAsync<Schema>();var version=(await Db.FindAsync<Schema>("version"))?.Value??"0";await Db.RunInTransactionAsync(c=>{c.CreateTable<SessionRow>();c.CreateTable<SolveRow>();c.CreateTable<TrainerRow>();c.CreateTable<SettingRow>();c.InsertOrReplace(new Schema{Key="version",Value="1"});});}
 public async Task<IReadOnlyList<Session>> GetSessionsAsync(){await InitializeAsync();return (await Db.Table<SessionRow>().OrderByDescending(x=>x.CreatedAt).ToListAsync()).Select(x=>x.Model).ToArray();}public async Task<IReadOnlyList<Solve>> GetSolvesAsync(string id){await InitializeAsync();return(await Db.Table<SolveRow>().Where(x=>x.SessionId==id).OrderBy(x=>x.CreatedAt).ToListAsync()).Select(x=>x.Model).ToArray();}
 public async Task SaveSessionAsync(Session x){await InitializeAsync();await Db.InsertOrReplaceAsync(SessionRow.From(x));}public async Task SaveSolveAsync(Solve x){await InitializeAsync();await Db.InsertOrReplaceAsync(SolveRow.From(x));}public async Task DeleteSolveAsync(string id){await InitializeAsync();await Db.DeleteAsync<SolveRow>(id);}public async Task<Settings> GetSettingsAsync(){await InitializeAsync();var x=await Db.FindAsync<SettingRow>("settings");return x is null?new():JsonSerializer.Deserialize<Settings>(x.Json,Json)??new();}public async Task SaveSettingsAsync(Settings s){await InitializeAsync();await Db.InsertOrReplaceAsync(new SettingRow{Key="settings",Json=JsonSerializer.Serialize(s,Json)});}
 public async Task ImportAsync(ImportResult x){await InitializeAsync();await Db.RunInTransactionAsync(c=>{foreach(var s in x.Sessions)c.InsertOrReplace(SessionRow.From(s));foreach(var s in x.Solves)c.InsertOrReplace(SolveRow.From(s));foreach(var t in x.TrainerStats)c.InsertOrReplace(new TrainerRow{Id=t.Id,Json=JsonSerializer.Serialize(t,Json),UpdatedAt=t.UpdatedAt});if(x.Settings is not null)c.InsertOrReplace(new SettingRow{Key="settings",Json=JsonSerializer.Serialize(x.Settings,Json)});});}
 public async Task<ExportFile> ExportAsync(){await InitializeAsync();var sessions=await GetSessionsAsync();var solves=(await Db.Table<SolveRow>().ToListAsync()).Select(x=>x.Model);var trainers=(await Db.Table<TrainerRow>().ToListAsync()).Select(x=>JsonSerializer.Deserialize<TrainerStat>(x.Json,Json)!).ToList();return Transfer.BuildExport(sessions,solves,trainers,await GetSettingsAsync());}
 [Table("schema_info")]class Schema{[PrimaryKey]public string Key{get;set;}="";public string Value{get;set;}="";}[Table("sessions")]class SessionRow{[PrimaryKey]public string Id{get;set;}="";public string Name{get;set;}="";public string Puzzle{get;set;}="333";public long CreatedAt{get;set;}public Session Model=>new(Id,Name,Puzzle,CreatedAt);public static SessionRow From(Session x)=>new(){Id=x.Id,Name=x.Name,Puzzle=x.Puzzle,CreatedAt=x.CreatedAt};}
 [Table("solves")]class SolveRow{[PrimaryKey]public string Id{get;set;}="";[Indexed]public string SessionId{get;set;}="";public string Puzzle{get;set;}="333";public string Scramble{get;set;}="";public long TimeMs{get;set;}public int Penalty{get;set;}public string? Comment{get;set;}public long CreatedAt{get;set;}public Solve Model=>new(Id,SessionId,Puzzle,Scramble,TimeMs,(CubeSolverPro.Core.Statistics.Penalty)Penalty,CreatedAt,Comment);public static SolveRow From(Solve x)=>new(){Id=x.Id,SessionId=x.SessionId,Puzzle=x.Puzzle,Scramble=x.Scramble,TimeMs=x.TimeMs,Penalty=(int)x.Penalty,Comment=x.Comment,CreatedAt=x.CreatedAt};}
 [Table("trainer_statistics")]class TrainerRow{[PrimaryKey]public string Id{get;set;}="";public string Json{get;set;}="";public long UpdatedAt{get;set;}}[Table("settings")]class SettingRow{[PrimaryKey]public string Key{get;set;}="";public string Json{get;set;}="";}}
